name: audius_flutter_client
description: A new Flutter project.

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  animated_rotation: ^2.0.0
  animations: ^2.0.0
  audio_service: ^0.17.0
  audio_session: ^0.1.0
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  http: ^0.13.2
  just_audio: ^0.7.4
  # json_annotation: ^4.0.1
  rxdart: ^0.26.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  # json_serializable: ^4.1.0

flutter:
  uses-material-design: true
  fonts:
      - family: 'Avenir Next LT Pro'
        fonts:
          - asset: assets/fonts/AvenirNextLTPro-Regular.otf
            style: normal
          - asset: assets/fonts/AvenirNextLTPro-Bold.otf
            weight: 700
          - asset: assets/fonts/AvenirNextLTPro-Demi-Bold.otf
            weight: 600
          - asset: assets/fonts/AvenirNextLTPro-Heavy.otf
            weight: 800
          - asset: assets/fonts/AvenirNextLTPro-Medium.otf
            weight: 500
          - asset: assets/fonts/AvenirNextLTPro-UltLt.otf
            weight: 200

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icons/application/audius_white.jpg"

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.